version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=petko
      - POSTGRES_DB=destinations-spots-db

  backend:
    build: .
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
