# Generated by Django 5.0.2 on 2024-03-05 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_modified'),
        ('feedback', '0003_rating_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'destination')},
        ),
    ]
