# Generated by Django 5.0.2 on 2024-02-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
