# Generated by Django 5.0.2 on 2024-03-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destination_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
