# Generated by Django 5.0.2 on 2024-03-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
